### ISSUE TITLE
data is very out of date and needs to be regenerated

### ISSUE THREAD

**Issue by karenetheridge** [sanko/acme-cpanauthors-acme-cpanauthors-authors#2]
Do you have code for fetching data regarding Acme::CPANAuthors::\* distributions from PAUSE or metacpan and generating the hash?  I'd be happy to work with you to set something up in this distribution to make it easier to regenerate the data.

cpan:ETHER

(I'll be sending a pull request to add a few missing entries that I've noticed, but it would be easier and more fun to write some code to update the full list.) :)

**Comment by sanko** [comment]
ACACA was tossed together by hand one groggy night in 2009. Today, I'd (lazily) scrape http://www.cpan.org/modules/02packages.details.txt with HTTP::Tiny or (wisely) use MetaCPAN::API.

I'll accept your pull request (thanks!) and see what I can whip up this weekend.

**Comment by karenetheridge** [comment]
I'm putting something together for Acme::CPANAuthors::Nonhuman that you can probably tap into... it's using a few levels of templating to turn the list of PAUSE ids (which I supply manually, but you could generate programmatically too) to get the list of associated names and then generate some html with a grid of avatar images.

I'll make a note to come back when I've got it ready and give you a PR! :)
